### ISSUE TITLE
如何加入apifox团队啊。。。。

### ISSUE THREAD

**Issue by zhaoyoushuai** [8pig/Vue3-admin#4]

**Comment by 8pig** [comment]
留下你的账号 我拉你进团队

**Comment by zhaixiankui** [comment]
414943516@qq.com

**Comment by zhaixiankui** [comment]
> 留下你的账号 我拉你进团队
[414943516@qq.com](mailto:414943516@qq.com)

**Comment by zhaoyoushuai** [comment]
> 留下你的账号 我拉你进团队

1164375084@qq.com

**Comment by wifigirl** [comment]
> 留下你的账号 我拉你进团队

215712160@qq.com

**Comment by yoZerY** [comment]
> 留下你的账号 我拉你进团队

yz583235075@qq.com

**Comment by jiuxuan00** [comment]
> 留下你的账号 我拉你进团队

117898271@qq.com

**Comment by 8pig** [comment]
各位不好意思  最近忙家里和备考 暂时中断迭代,   4/16后继续更新  不好意思

**Comment by xmlxin** [comment]
1126339399@qq.com

**Comment by xmlxin** [comment]
> 留下你的账号 我拉你进团队

1126339399@qq.com

**Comment by KarmaLost** [comment]
> 留下你的账号 我拉你进团队
1982889898@qq.com

**Comment by 8pig** [comment]
> 



> [1126339399@qq.com](mailto:1126339399@qq.com)

已经更新开发文档 导入apifox.json 并设置代理URL 即可运行

**Comment by 8pig** [comment]
> [1126339399@qq.com](mailto:1126339399@qq.com)


已经更新开发文档 导入apifox.json 并设置代理URL 即可运行

**Comment by 8pig** [comment]
> > 留下你的账号 我拉你进团队
> 
> [117898271@qq.com](mailto:117898271@qq.com)


已经更新开发文档 导入apifox.json 并设置代理URL 即可运行

**Comment by 8pig** [comment]
> > 留下你的账号 我拉你进团队
> 
> [yz583235075@qq.com](mailto:yz583235075@qq.com)


已经更新开发文档 导入apifox.json 并设置代理URL 即可运行

**Comment by 8pig** [comment]
> > 留下你的账号 我拉你进团队
> 
> [1164375084@qq.com](mailto:1164375084@qq.com)


已经更新开发文档 导入apifox.json 并设置代理URL 即可运行

**Comment by 8pig** [comment]
> > 留下你的账号 我拉你进团队
> > [414943516@qq.com](mailto:414943516@qq.com)


已经更新开发文档 导入apifox.json 并设置代理URL 即可运行
