### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Charlene12345** [8pig/Vue3-admin#5]
在吾爱破解看到你的，《基于 Vue3 ，打造前台+中台通用提效解决方案》能不能发我一下？谢谢：）

大家好，在此收集基于Vue3打造前台中台通用提效解决方案
有效期截止到2022年6月17日15:33，麻烦在此之前点击以下链接将文件发送给我，支持发送任意格式的文件，感谢~
链接：https://pan.baidu.com/disk/main#/transfer/send?surl=ACMAAAAAAA5ffA
来自：若夏12345

**Comment by 8pig** [comment]
> 在吾爱破解看到你的，《基于 Vue3 ，打造前台+中台通用提效解决方案》能不能发我一下？谢谢：）
> 
> 大家好，在此收集基于Vue3打造前台中台通用提效解决方案 有效期截止到2022年6月17日15:33，麻烦在此之前点击以下链接将文件发送给我，支持发送任意格式的文件，感谢~ 链接：https://pan.baidu.com/disk/main#/transfer/send?surl=ACMAAAAAAA5ffA 来自：若夏12345

发了

**Comment by xn213** [comment]
> 

酷(库)主，楼主你好 能不能帮忙转发我一下：谢谢
@8pig @Charlene12345 
大家好，在此收集基于Vue3最新标准实现后台前端综合解
有效期截止到2022年7月26日23:01，麻烦在此之前点击以下链接将文件发送给我，支持发送任意格式的文件，感谢~
链接：https://pan.baidu.com/disk/main#/transfer/send?surl=AAgAAAAAAA6kFw
来自：xn213

**Comment by 8pig** [comment]
done
